// Centralized styles for Lumina app
import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS } from '../../theme.js';

const styles = StyleSheet.create({
  container: { flex: 1 },
  containerInner: { flex: 1 },
  screenWrapper: { flex: 1 },
  screenContainer: { flex: 1, paddingHorizontal: 20, paddingTop: 10, backgroundColor: 'transparent' },
  screenTitle: { fontSize: 36, fontWeight: '400', color: COLORS.text.primary, marginBottom: 20, fontFamily: 'CormorantGaramond_400Regular' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerTitle: { fontSize: 36, fontWeight: '400', color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular', textTransform: 'lowercase' },
  headerSubtitle: { fontSize: 16, fontWeight: '300', color: COLORS.text.secondary, fontStyle: 'italic', fontFamily: 'CormorantGaramond_400Regular' },
  notificationButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: COLORS.bg.card, justifyContent: 'center', alignItems: 'center', ...SHADOWS.card },
  statusCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 16, marginBottom: 24, ...SHADOWS.card },
  statusDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: COLORS.accent.success, marginRight: 12 },
  statusText: { flex: 1, fontSize: 16, fontWeight: '600', color: '#4CAF50', fontFamily: 'CormorantGaramond_400Regular' },
  statusTime: { fontSize: 12, color: COLORS.text.secondary, fontFamily: 'CormorantGaramond_400Regular' },
  sectionTitle: { fontSize: 20, fontWeight: '700', color: COLORS.text.primary, marginBottom: 12, marginTop: 8, fontFamily: 'CormorantGaramond_400Regular' },
  quickActions: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 },
  quickAction: { flex: 1, alignItems: 'center', backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 16, marginHorizontal: 4, ...SHADOWS.card },
  quickActionIcon: { width: 52, height: 52, borderRadius: 26, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  quickActionText: { fontSize: 12, color: COLORS.text.primary, textAlign: 'center', fontWeight: '500', fontFamily: 'CormorantGaramond_400Regular' },
  card: { backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 16, marginBottom: 12, ...SHADOWS.card },
  cardHeader: { flexDirection: 'row', alignItems: 'center' },
  iconContainer: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  cardTitleContainer: { flex: 1 },
  cardTitle: { fontSize: 16, fontWeight: '600', color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  cardSubtitle: { fontSize: 13, color: COLORS.text.secondary, marginTop: 2, fontFamily: 'CormorantGaramond_400Regular' },
  cardContent: { marginTop: 12 },
  cardAction: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 12, borderTopWidth: 1, borderTopColor: COLORS.borderLight },
  cardActionText: { fontSize: 14, color: COLORS.accent.primary, fontFamily: 'CormorantGaramond_400Regular' },
  tabBar: { flexDirection: 'row', backgroundColor: COLORS.bg.secondary, paddingBottom: 0, paddingTop: 10, ...SHADOWS.card },
  tabButton: { flex: 1, alignItems: 'center', paddingVertical: 8 },
  tabLabel: { fontSize: 11, color: COLORS.text.muted, marginTop: 4, fontWeight: '500', fontFamily: 'CormorantGaramond_400Regular' },
  tabLabelActive: { color: COLORS.accent.primary },
  sosTabButtonContainer: { flex: 1, alignItems: 'center', justifyContent: 'flex-end', marginBottom: 8 },
  sosTabButton: { width: 60, height: 60, borderRadius: 30, backgroundColor: COLORS.accent.danger, justifyContent: 'center', alignItems: 'center', marginTop: -30, shadowColor: COLORS.accent.danger, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.8, shadowRadius: 15, elevation: 10, borderWidth: 3, borderColor: COLORS.bg.secondary },
  sosScreenContainer: { flex: 1, backgroundColor: 'transparent', paddingHorizontal: 20, paddingTop: 20, alignItems: 'center' },
  sosScreenTitle: { fontSize: 32, fontWeight: 'bold', color: COLORS.text.primary, marginBottom: 8, fontFamily: 'CormorantGaramond_400Regular' },
  sosScreenSubtitle: { fontSize: 16, color: COLORS.text.secondary, marginBottom: 40, textAlign: 'center', fontFamily: 'CormorantGaramond_400Regular' },
  sosMainButton: { width: 180, height: 180, borderRadius: 90, backgroundColor: COLORS.accent.danger, justifyContent: 'center', alignItems: 'center', shadowColor: COLORS.accent.danger, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 1, shadowRadius: 30, elevation: 15, marginBottom: 50 },
  sosMainButtonText: { color: COLORS.text.primary, fontSize: 32, fontWeight: 'bold', marginTop: 8, fontFamily: 'CormorantGaramond_400Regular' },
  emergencyContactsTitle: { fontSize: 18, fontWeight: '600', color: COLORS.text.primary, alignSelf: 'flex-start', marginBottom: 16, fontFamily: 'CormorantGaramond_400Regular' },
  emergencyContactItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 16, marginBottom: 12, width: '100%', ...SHADOWS.card },
  emergencyContactIcon: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  emergencyContactInfo: { flex: 1 },
  emergencyContactName: { fontSize: 18, fontWeight: '600', color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  emergencyContactDesc: { fontSize: 14, color: COLORS.text.secondary, marginTop: 2, fontFamily: 'CormorantGaramond_400Regular' },
  mapContainer: { flex: 1 },
  map: { flex: 1 },
  mapControls: { position: 'absolute', top: 20, right: 20 },
  controlButton: { backgroundColor: COLORS.bg.cardSolid, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, flexDirection: 'row', alignItems: 'center', gap: 6, ...SHADOWS.card },
  controlButtonActive: { backgroundColor: 'rgba(255, 140, 0, 0.3)', borderColor: '#FF8C00' },
  controlButtonIcon: { fontSize: 16 },
  controlButtonText: { color: COLORS.text.primary, fontSize: 14, fontWeight: '500', fontFamily: 'CormorantGaramond_400Regular' },
  legend: { position: 'absolute', bottom: 20, left: 20, backgroundColor: COLORS.bg.cardSolid, borderRadius: 16, padding: 16, ...SHADOWS.card },
  legendTitle: { color: COLORS.text.primary, fontWeight: '600', marginBottom: 10, fontSize: 14, fontFamily: 'CormorantGaramond_400Regular' },
  legendItem: { flexDirection: 'row', alignItems: 'center', marginVertical: 4 },
  legendDot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 },
  legendText: { color: COLORS.text.secondary, fontSize: 12, fontFamily: 'CormorantGaramond_400Regular' },
  routePanel: { position: 'absolute', top: 10, left: 16, right: 16, backgroundColor: COLORS.bg.cardSolid, borderRadius: 16, padding: 12, ...SHADOWS.card },
  routeInputContainer: { marginBottom: 8 },
  routeInputWrapper: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  routeDot: { width: 10, height: 10, borderRadius: 5 },
  routeInput: { flex: 1, backgroundColor: COLORS.iconBg.peach, borderRadius: 10, padding: 10 },
  routeInputText: { color: COLORS.text.primary, fontSize: 13, fontFamily: 'CormorantGaramond_400Regular' },
  routeInputPlaceholder: { color: COLORS.text.muted, fontSize: 13, fontFamily: 'CormorantGaramond_400Regular' },
  routeInputDivider: { width: 2, height: 12, backgroundColor: COLORS.border, marginLeft: 4, marginVertical: 3 },
  findRouteButton: { backgroundColor: '#A8E6CF', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 24, gap: 6, shadowColor: '#A8E6CF', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  findRouteButtonDisabled: { backgroundColor: COLORS.text.muted },
  findRouteButtonText: { color: '#2D2D2D', fontSize: 14, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  startMarker: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#A8E6CF', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#fff' },
  endMarker: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#FFB5A7', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#fff' },
  blueLightMarker: { width: 22, height: 22, borderRadius: 11, backgroundColor: '#B8DCEF', justifyContent: 'center', alignItems: 'center', borderWidth: 1.5, borderColor: '#fff' },
  groupMarker: { width: 26, height: 26, borderRadius: 13, backgroundColor: '#D4B8E8', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#fff' },
  locationPickerOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.8)', justifyContent: 'center', alignItems: 'center' },
  locationPicker: { backgroundColor: COLORS.bg.card, borderRadius: 20, width: '85%', maxHeight: '70%', overflow: 'hidden', ...SHADOWS.card },
  locationPickerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  locationPickerTitle: { color: COLORS.text.primary, fontSize: 18, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  locationList: { padding: 10 },
  locationItem: { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 12, borderBottomWidth: 1, borderBottomColor: COLORS.borderLight },
  presetMatchItem: { backgroundColor: 'rgba(255, 107, 53, 0.1)', borderRadius: 10, marginHorizontal: 10, marginVertical: 4, borderWidth: 1, borderColor: 'rgba(255, 107, 53, 0.3)' },
  locationItemText: { color: COLORS.text.primary, fontSize: 16, fontFamily: 'CormorantGaramond_400Regular' },
  locationItemContent: { flex: 1 },
  locationItemSubtext: { color: COLORS.text.muted, fontSize: 12, marginTop: 2, fontFamily: 'CormorantGaramond_400Regular' },
  locationSectionTitle: { color: COLORS.text.muted, fontSize: 12, fontWeight: '600', textTransform: 'uppercase', paddingHorizontal: 16, paddingTop: 16, paddingBottom: 8, letterSpacing: 0.5, fontFamily: 'CormorantGaramond_400Regular' },
  myLocationItem: { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 12, backgroundColor: 'rgba(30, 64, 175, 0.1)', marginHorizontal: 10, marginTop: 10, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(30, 64, 175, 0.3)' },
  myLocationText: { color: '#1E40AF', fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  searchInputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.iconBg.peach, borderRadius: 12, paddingHorizontal: 16, marginHorizontal: 20, marginBottom: 10, gap: 12 },
  searchInput: { flex: 1, color: COLORS.text.primary, fontSize: 16, paddingVertical: 14, fontFamily: 'CormorantGaramond_400Regular' },
  loadingText: { color: COLORS.text.muted, fontSize: 14, fontFamily: 'CormorantGaramond_400Regular' },
  routeInfoPanel: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: COLORS.bg.cardSolid, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 16, paddingBottom: 24, ...SHADOWS.card },
  routeInfoHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  routeInfoTitle: { color: COLORS.accent.primary, fontSize: 15, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  routeInfoStats: { flexDirection: 'row', backgroundColor: COLORS.iconBg.peach, borderRadius: 12, padding: 12, marginBottom: 12 },
  routeInfoStat: { flex: 1, alignItems: 'center' },
  routeInfoStatValue: { color: COLORS.text.primary, fontSize: 18, fontWeight: 'bold', fontFamily: 'CormorantGaramond_400Regular' },
  routeInfoStatLabel: { color: COLORS.text.secondary, fontSize: 11, marginTop: 2, fontFamily: 'CormorantGaramond_400Regular' },
  routeInfoStatDivider: { width: 1, backgroundColor: COLORS.border },
  startWalkingButton: { backgroundColor: '#A8E6CF', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderRadius: 24, gap: 6, shadowColor: '#A8E6CF', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  startWalkingButtonText: { color: '#2D2D2D', fontSize: 14, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  navigationPanel: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: COLORS.bg.cardSolid, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 16, paddingBottom: 24, ...SHADOWS.card },
  navigationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  navigationHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  navigationTitle: { color: COLORS.accent.primary, fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  exitNavButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255, 59, 48, 0.15)', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, gap: 4 },
  exitNavButtonText: { color: COLORS.accent.danger, fontSize: 13, fontWeight: '500', fontFamily: 'CormorantGaramond_400Regular' },
  navigationStep: { flexDirection: 'row', backgroundColor: COLORS.iconBg.peach, borderRadius: 12, padding: 12, marginBottom: 10, gap: 12 },
  stepIndicator: { flexDirection: 'row', alignItems: 'baseline' },
  stepNumber: { color: COLORS.accent.primary, fontSize: 24, fontWeight: 'bold', fontFamily: 'CormorantGaramond_400Regular' },
  stepTotal: { color: COLORS.text.muted, fontSize: 14, fontFamily: 'CormorantGaramond_400Regular' },
  stepContent: { flex: 1 },
  stepInstruction: { color: COLORS.text.primary, fontSize: 15, fontWeight: '600', marginBottom: 2, fontFamily: 'CormorantGaramond_400Regular' },
  stepDetail: { color: COLORS.text.secondary, fontSize: 13, lineHeight: 18, fontFamily: 'CormorantGaramond_400Regular' },
  stepDistance: { color: COLORS.accent.primary, fontSize: 13, fontWeight: '500', marginTop: 4, fontFamily: 'CormorantGaramond_400Regular' },
  navigationControls: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  navControlButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.iconBg.lavender, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18, gap: 4 },
  navControlButtonDisabled: { backgroundColor: COLORS.borderLight },
  navControlText: { color: COLORS.text.primary, fontSize: 13, fontWeight: '500', fontFamily: 'CormorantGaramond_400Regular' },
  navControlTextDisabled: { color: COLORS.text.muted, fontFamily: 'CormorantGaramond_400Regular' },
  progressDots: { flexDirection: 'row', gap: 4, flexWrap: 'wrap', justifyContent: 'center', maxWidth: 120 },
  progressDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.borderLight },
  progressDotActive: { backgroundColor: COLORS.accent.primary, width: 14 },
  progressDotCompleted: { backgroundColor: 'rgba(255, 155, 138, 0.5)' },
  liveDistanceBanner: { backgroundColor: COLORS.accent.primary, borderRadius: 12, padding: 12, marginBottom: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  liveDistanceText: { color: COLORS.text.primary, fontSize: 24, fontWeight: 'bold', fontFamily: 'CormorantGaramond_400Regular' },
  liveDistanceLabel: { color: 'rgba(255, 255, 255, 0.9)', fontSize: 14, fontFamily: 'CormorantGaramond_400Regular' },
  callout: { padding: 10, minWidth: 160 },
  calloutTitle: { fontWeight: 'bold', fontSize: 14, marginBottom: 4, fontFamily: 'CormorantGaramond_400Regular' },
  calloutName: { fontSize: 13, color: '#333', fontFamily: 'CormorantGaramond_400Regular' },
  calloutDistance: { fontSize: 12, color: '#666', marginTop: 2, fontFamily: 'CormorantGaramond_400Regular' },
  directionsPanel: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: COLORS.bg.cardSolid, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, paddingBottom: 40, ...SHADOWS.card },
  directionsPanelHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  directionsPanelTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  directionsPanelSubtitle: { fontSize: 14, color: COLORS.text.secondary, marginTop: 4, fontFamily: 'CormorantGaramond_400Regular' },
  directionsInfo: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 20 },
  directionsInfoText: { fontSize: 16, color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  startButton: { backgroundColor: COLORS.accent.primary, paddingVertical: 16, borderRadius: 24, alignItems: 'center', ...SHADOWS.button },
  startButtonText: { color: COLORS.text.primary, fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  createButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.accent.primary, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 24, gap: 6, ...SHADOWS.button },
  createButtonText: { color: COLORS.text.primary, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  infoCard: { flexDirection: 'row', backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 16, marginBottom: 24, gap: 12, ...SHADOWS.card },
  infoCardContent: { flex: 1 },
  infoCardTitle: { fontSize: 16, fontWeight: '600', color: COLORS.accent.primary, fontFamily: 'CormorantGaramond_400Regular' },
  infoCardText: { fontSize: 14, color: COLORS.text.secondary, marginTop: 4, fontFamily: 'CormorantGaramond_400Regular' },
  groupDetails: { flexDirection: 'column', gap: 4, marginBottom: 12 },
  groupDetailItem: { flexDirection: 'row', alignItems: 'center', gap: 6, flex: 1 },
  groupDetailText: { fontSize: 13, color: COLORS.text.secondary, flex: 1, fontFamily: 'CormorantGaramond_400Regular' },
  modalOverlay: { flex: 1, backgroundColor: COLORS.overlay, justifyContent: 'center', alignItems: 'center' },
  zoneInfoPin: { width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(0, 0, 0, 0.7)', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: 'rgba(255, 255, 255, 0.4)' },
  zoneInfoModal: { backgroundColor: COLORS.bg.cardSolid, borderRadius: 20, padding: 20, width: '85%', maxWidth: 340, ...SHADOWS.card },
  zoneInfoHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  zoneInfoDot: { width: 12, height: 12, borderRadius: 6, marginRight: 10 },
  zoneInfoTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.text.primary, flex: 1, fontFamily: 'CormorantGaramond_400Regular' },
  zoneInfoDangerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: COLORS.iconBg.peach, borderRadius: 12, padding: 14, marginBottom: 16 },
  zoneInfoDangerLabel: { fontSize: 14, color: COLORS.text.secondary, fontFamily: 'CormorantGaramond_400Regular' },
  zoneInfoDangerValue: { fontSize: 24, fontWeight: 'bold', fontFamily: 'CormorantGaramond_400Regular' },
  zoneInfoSection: { marginBottom: 16 },
  zoneInfoSectionTitle: { fontSize: 14, fontWeight: '600', color: COLORS.text.secondary, marginBottom: 8, fontFamily: 'CormorantGaramond_400Regular' },
  zoneInfoCrimeItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  zoneInfoCrimeBullet: { color: COLORS.accent.danger, fontSize: 16, marginRight: 8, fontFamily: 'CormorantGaramond_400Regular' },
  zoneInfoCrimeText: { fontSize: 15, color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  zoneInfoPeakText: { fontSize: 14, color: COLORS.text.primary, lineHeight: 20, fontFamily: 'CormorantGaramond_400Regular' },
  zoneInfoCloseButton: { backgroundColor: COLORS.bg.secondary, borderRadius: 12, padding: 14, alignItems: 'center', marginTop: 4 },
  zoneInfoCloseText: { color: COLORS.text.primary, fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  modalContent: { backgroundColor: COLORS.bg.card, borderRadius: 24, padding: 32, alignItems: 'center', width: '85%', ...SHADOWS.card },
  modalClose: { position: 'absolute', top: 16, right: 16 },
  modalTitle: { fontSize: 24, fontWeight: 'bold', color: COLORS.text.primary, marginTop: 16, fontFamily: 'CormorantGaramond_400Regular' },
  modalText: { fontSize: 16, color: COLORS.text.secondary, marginTop: 8, fontFamily: 'CormorantGaramond_400Regular' },
  modalSubtext: { fontSize: 14, color: COLORS.accent.success, marginTop: 4, fontFamily: 'CormorantGaramond_400Regular' },
  joinButton: { backgroundColor: COLORS.accent.primary, paddingHorizontal: 48, paddingVertical: 16, borderRadius: 24, marginTop: 24, ...SHADOWS.button },
  joinButtonText: { color: COLORS.text.primary, fontSize: 16, fontWeight: 'bold', fontFamily: 'CormorantGaramond_400Regular' },
  joinedContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 24, gap: 10 },
  joinedText: { color: COLORS.accent.primary, fontSize: 16, fontWeight: 'bold', fontFamily: 'CormorantGaramond_400Regular' },
  joinedBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.iconBg.mint, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, gap: 6 },
  joinedBadgeText: { color: COLORS.accent.primary, fontSize: 14, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  emptyState: { padding: 24, alignItems: 'center' },
  emptyStateText: { color: COLORS.text.muted, fontSize: 14, fontFamily: 'CormorantGaramond_400Regular' },
  createFormContainer: { width: '100%', marginTop: 20 },
  createFormLabel: { color: COLORS.text.secondary, fontSize: 12, fontWeight: '600', marginBottom: 8, marginTop: 16, fontFamily: 'CormorantGaramond_400Regular' },
  createFormInput: { backgroundColor: COLORS.iconBg.peach, borderRadius: 12, padding: 14, color: COLORS.text.primary, fontSize: 16, fontFamily: 'CormorantGaramond_400Regular' },
  createFormInputText: { color: COLORS.text.primary, fontSize: 16, fontFamily: 'CormorantGaramond_400Regular' },
  createFormPlaceholder: { color: COLORS.text.muted, fontSize: 16, fontFamily: 'CormorantGaramond_400Regular' },
  destinationPickerList: { maxHeight: 150, marginTop: 8, backgroundColor: COLORS.iconBg.peach, borderRadius: 12 },
  destinationPickerItem: { flexDirection: 'row', alignItems: 'center', padding: 12, gap: 10, borderBottomWidth: 1, borderBottomColor: COLORS.borderLight },
  destinationPickerText: { color: COLORS.text.primary, fontSize: 14, flex: 1, fontFamily: 'CormorantGaramond_400Regular' },
  createFormInputRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  createLocationHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%', marginBottom: 16 },
  createLocationTitle: { color: COLORS.text.primary, fontSize: 18, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  createLocationList: { width: '100%', maxHeight: 350, marginTop: 12 },
  emergencyOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.9)', justifyContent: 'center', alignItems: 'center' },
  emergencyContent: { backgroundColor: '#1a1a2e', borderRadius: 24, padding: 32, alignItems: 'center', width: '85%', borderWidth: 2, borderColor: COLORS.accent.danger },
  emergencyTitle: { fontSize: 24, fontWeight: 'bold', color: COLORS.accent.danger, marginTop: 16, fontFamily: 'CormorantGaramond_400Regular' },
  emergencyText: { fontSize: 16, color: COLORS.text.primary, marginTop: 8, textAlign: 'center', fontFamily: 'CormorantGaramond_400Regular' },
  callButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.text.primary, paddingHorizontal: 32, paddingVertical: 14, borderRadius: 30, marginTop: 24, gap: 8 },
  callButtonText: { color: COLORS.accent.danger, fontSize: 18, fontWeight: 'bold', fontFamily: 'CormorantGaramond_400Regular' },
  cancelButton: { paddingHorizontal: 32, paddingVertical: 12, marginTop: 16 },
  cancelButtonText: { color: COLORS.text.secondary, fontSize: 16, fontFamily: 'CormorantGaramond_400Regular' },
  profileCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 20, marginBottom: 20, ...SHADOWS.card },
  avatarContainer: { width: 70, height: 70, borderRadius: 35, backgroundColor: COLORS.accent.primary, justifyContent: 'center', alignItems: 'center' },
  profileInfo: { flex: 1, marginLeft: 16 },
  profileName: { fontSize: 20, fontWeight: '600', color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  profileEmail: { fontSize: 14, color: COLORS.text.secondary, marginTop: 2, fontFamily: 'CormorantGaramond_400Regular' },
  editButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, borderColor: COLORS.accent.primary },
  editButtonText: { color: COLORS.accent.primary, fontWeight: '500', fontFamily: 'CormorantGaramond_400Regular' },
  statsContainer: { flexDirection: 'row', backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 20, marginBottom: 24, ...SHADOWS.card },
  statItem: { flex: 1, alignItems: 'center' },
  statNumber: { fontSize: 28, fontWeight: 'bold', color: COLORS.accent.primary, fontFamily: 'CormorantGaramond_400Regular' },
  statLabel: { fontSize: 12, color: COLORS.text.secondary, marginTop: 4, fontFamily: 'CormorantGaramond_400Regular' },
  statDivider: { width: 1, backgroundColor: COLORS.border },
  settingsCard: { backgroundColor: COLORS.bg.card, borderRadius: 16, marginBottom: 16, overflow: 'hidden', ...SHADOWS.card },
  settingItem: { flexDirection: 'row', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: COLORS.borderLight },
  settingIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: COLORS.iconBg.peach, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  settingContent: { flex: 1 },
  settingTitle: { fontSize: 16, color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  settingSubtitle: { fontSize: 13, color: COLORS.text.muted, marginTop: 2, fontFamily: 'CormorantGaramond_400Regular' },
  departureTimeContainer: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  departureTimeOption: { flex: 1, paddingVertical: 12, paddingHorizontal: 8, borderRadius: 12, backgroundColor: COLORS.iconBg.peach, alignItems: 'center' },
  departureTimeOptionActive: { backgroundColor: COLORS.accent.primary },
  departureTimeText: { color: COLORS.text.secondary, fontSize: 14, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  departureTimeTextActive: { color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  departureTimeHint: { fontSize: 12, color: COLORS.text.muted, marginTop: 8, textAlign: 'center', fontFamily: 'CormorantGaramond_400Regular' },
  countdownBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.iconBg.peach, paddingVertical: 6, paddingHorizontal: 10, borderRadius: 8, gap: 6, marginTop: 8, marginBottom: 4 },
  countdownText: { color: COLORS.accent.primary, fontSize: 12, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  modalCountdown: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: COLORS.iconBg.peach, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, marginTop: 8 },
  modalCountdownText: { color: COLORS.accent.primary, fontSize: 14, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  memberListContainer: { width: '100%', marginTop: 16 },
  memberListTitle: { fontSize: 14, color: COLORS.text.muted, fontWeight: '600', marginBottom: 12, textTransform: 'uppercase', letterSpacing: 1, fontFamily: 'CormorantGaramond_400Regular' },
  memberItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  memberInfo: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  memberName: { color: COLORS.text.primary, fontSize: 16, fontFamily: 'CormorantGaramond_400Regular' },
  memberStatus: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, gap: 4 },
  memberStatusReady: { backgroundColor: COLORS.iconBg.mint },
  memberStatusWaiting: { backgroundColor: COLORS.iconBg.peach },
  memberStatusText: { fontSize: 12, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  memberStatusTextReady: { color: '#4CAF50', fontFamily: 'CormorantGaramond_400Regular' },
  memberStatusTextWaiting: { color: '#FF9800', fontFamily: 'CormorantGaramond_400Regular' },
  memberSubtext: { color: COLORS.text.muted, fontSize: 14, textAlign: 'center', paddingVertical: 12, fontFamily: 'CormorantGaramond_400Regular' },
  imHereButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.accent.primary, paddingVertical: 14, borderRadius: 24, marginTop: 16, gap: 8, ...SHADOWS.button },
  imHereButtonText: { color: COLORS.text.primary, fontSize: 16, fontWeight: 'bold', fontFamily: 'CormorantGaramond_400Regular' },
  viewRouteButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.iconBg.lavender, paddingVertical: 14, borderRadius: 24, marginTop: 12, gap: 8 },
  viewRouteButtonText: { color: COLORS.text.primary, fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  notificationBadge: { position: 'absolute', top: -2, right: -2, backgroundColor: COLORS.accent.danger, borderRadius: 10, minWidth: 18, height: 18, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 4 },
  notificationBadgeText: { color: COLORS.text.primary, fontSize: 10, fontWeight: 'bold', fontFamily: 'CormorantGaramond_400Regular' },
  incidentFeedContainer: { flex: 1, backgroundColor: 'transparent' },
  feedHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: 16, paddingBottom: 12 },
  backButton: { padding: 4 },
  feedTitle: { fontSize: 22, fontWeight: 'bold', color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  filterContainer: { flexDirection: 'row', paddingHorizontal: 16, marginBottom: 12, gap: 8 },
  filterChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: COLORS.bg.card, ...SHADOWS.card },
  filterChipActive: { backgroundColor: COLORS.accent.primary, borderColor: COLORS.accent.primary },
  filterChipText: { color: COLORS.text.secondary, fontSize: 14, fontWeight: '500', fontFamily: 'CormorantGaramond_400Regular' },
  filterChipTextActive: { color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  incidentList: { flex: 1, paddingHorizontal: 16 },
  incidentCard: { backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 14, marginBottom: 12, borderLeftWidth: 4, ...SHADOWS.card },
  incidentHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  incidentTypeIcon: { fontSize: 18 },
  incidentTitle: { flex: 1, fontSize: 15, fontWeight: '600', color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  incidentBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
  incidentBadgeVTPD: { backgroundColor: 'rgba(30, 64, 175, 0.2)' },
  incidentBadgeCommunity: { backgroundColor: 'rgba(255, 255, 255, 0.1)' },
  incidentBadgeText: { fontSize: 10, fontWeight: '600', color: COLORS.text.primary, fontFamily: 'CormorantGaramond_400Regular' },
  incidentMeta: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 6 },
  incidentLocation: { color: COLORS.text.secondary, fontSize: 13, flex: 1, fontFamily: 'CormorantGaramond_400Regular' },
  incidentTime: { color: COLORS.text.muted, fontSize: 12, fontFamily: 'CormorantGaramond_400Regular' },
  incidentDescription: { color: COLORS.text.secondary, fontSize: 13, lineHeight: 19, marginBottom: 10, fontFamily: 'CormorantGaramond_400Regular' },
  incidentFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  verifyCount: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, gap: 4 },
  verifyCountText: { color: COLORS.text.muted, fontSize: 13, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  verifyButton: { backgroundColor: 'rgba(255, 107, 53, 0.15)', paddingHorizontal: 14, paddingVertical: 6, borderRadius: 12 },
  verifyButtonText: { color: COLORS.accent.primary, fontSize: 13, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  fab: { position: 'absolute', bottom: 24, right: 20, width: 56, height: 56, borderRadius: 28, backgroundColor: COLORS.accent.primary, justifyContent: 'center', alignItems: 'center', ...SHADOWS.button },
  reportModalTitle: { fontSize: 22, fontWeight: 'bold', color: COLORS.text.primary, marginTop: 8, marginBottom: 4, fontFamily: 'CormorantGaramond_400Regular' },
  reportModalSubtitle: { fontSize: 14, color: COLORS.text.secondary, marginBottom: 20, fontFamily: 'CormorantGaramond_400Regular' },
  typeGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10, width: '100%' },
  typeButton: { width: '48%', backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 16, alignItems: 'center', ...SHADOWS.card },
  typeButtonIcon: { fontSize: 28, marginBottom: 8 },
  typeButtonLabel: { fontSize: 12, color: COLORS.text.primary, textAlign: 'center', fontWeight: '500', fontFamily: 'CormorantGaramond_400Regular' },
  reportInput: { width: '100%', backgroundColor: COLORS.bg.card, borderRadius: 16, padding: 16, color: COLORS.text.primary, fontSize: 16, marginBottom: 20, fontFamily: 'CormorantGaramond_400Regular', ...SHADOWS.card },
  reportNavButtons: { flexDirection: 'row', gap: 12, width: '100%' },
  reportNavButton: { flex: 1, paddingVertical: 14, borderRadius: 24, alignItems: 'center', backgroundColor: COLORS.bg.card, ...SHADOWS.card },
  reportNavButtonPrimary: { backgroundColor: COLORS.accent.primary, ...SHADOWS.button },
  reportNavButtonText: { color: COLORS.text.secondary, fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  reportNavButtonTextPrimary: { color: COLORS.text.primary, fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  authContainer: { flex: 1 },
  authSafeArea: { flex: 1, paddingHorizontal: 30 },
  authScrollContent: { flexGrow: 1, paddingBottom: 40 },
  authBackButton: { flexDirection: 'row', alignItems: 'center', marginTop: 16, marginBottom: 20 },
  authBackText: { fontSize: 16, color: COLORS.text.primary, marginLeft: 4, fontFamily: 'CormorantGaramond_400Regular' },
  authFormContainer: { flex: 1, justifyContent: 'center' },
  authTitle: { fontSize: 32, fontWeight: '600', color: COLORS.text.primary, marginBottom: 8, fontFamily: 'CormorantGaramond_400Regular', textAlign: 'center' },
  authSubtitle: { fontSize: 16, color: COLORS.text.secondary, marginBottom: 32, fontFamily: 'CormorantGaramond_400Regular', textAlign: 'center' },
  authInput: { backgroundColor: COLORS.iconBg.peach, borderRadius: 16, paddingHorizontal: 20, paddingVertical: 16, fontSize: 16, fontFamily: 'CormorantGaramond_400Regular', color: COLORS.text.primary, marginBottom: 16 },
  authButtonPrimary: { backgroundColor: COLORS.accent.primary, paddingVertical: 16, borderRadius: 24, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', marginTop: 8, ...SHADOWS.button },
  authButtonPrimaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  authButtonSecondary: { backgroundColor: 'transparent', paddingVertical: 16, alignItems: 'center', marginTop: 8 },
  authButtonSecondaryText: { color: COLORS.accent.primary, fontSize: 16, fontFamily: 'CormorantGaramond_400Regular' },
  authButtonDisabled: { opacity: 0.5 },
  forgotPassword: { alignItems: 'center', marginTop: 20 },
  forgotPasswordText: { color: COLORS.accent.primary, fontSize: 14, fontFamily: 'CormorantGaramond_400Regular' },
  welcomeLogoContainer: { alignItems: 'center', marginBottom: 60, marginTop: 80 },
  welcomeIconCircle: { width: 120, height: 120, borderRadius: 60, backgroundColor: COLORS.iconBg.peach, justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  welcomeTitle: { fontSize: 48, fontFamily: 'CormorantGaramond_400Regular', color: COLORS.text.primary },
  welcomeSubtitle: { fontSize: 18, fontFamily: 'CormorantGaramond_400Regular', color: COLORS.text.secondary, marginTop: 8 },
  welcomeButtons: { gap: 16 },
  authStepIndicator: { flexDirection: 'row', justifyContent: 'center', gap: 8, marginBottom: 32 },
  authStepDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.border },
  authStepDotActive: { backgroundColor: COLORS.accent.primary, width: 24 },
  termsCard: { backgroundColor: COLORS.bg.card, borderRadius: 20, padding: 20, marginBottom: 24, ...SHADOWS.card },
  termsScrollView: { maxHeight: 250 },
  termsText: { fontSize: 14, fontFamily: 'CormorantGaramond_400Regular', color: COLORS.text.secondary, lineHeight: 22 },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16, paddingHorizontal: 4 },
  checkbox: { width: 24, height: 24, borderRadius: 6, borderWidth: 2, borderColor: COLORS.accent.primary, alignItems: 'center', justifyContent: 'center' },
  checkboxChecked: { backgroundColor: COLORS.accent.primary },
  checkboxLabel: { fontSize: 14, fontFamily: 'CormorantGaramond_400Regular', color: COLORS.text.primary, flex: 1 },
  authNavButtons: { flexDirection: 'row', gap: 12, marginTop: 24 },
  authNavButton: { flex: 1, paddingVertical: 14, borderRadius: 24, alignItems: 'center', backgroundColor: COLORS.bg.card, ...SHADOWS.card },
  authNavButtonPrimary: { flex: 1, paddingVertical: 14, borderRadius: 24, alignItems: 'center', backgroundColor: COLORS.accent.primary, ...SHADOWS.button },
  authNavButtonText: { color: COLORS.text.secondary, fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  authNavButtonPrimaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600', fontFamily: 'CormorantGaramond_400Regular' },
  locationPermissionContainer: { alignItems: 'center', paddingVertical: 40 },
  locationIconCircle: { width: 100, height: 100, borderRadius: 50, backgroundColor: COLORS.iconBg.peach, justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  locationDescription: { fontSize: 16, fontFamily: 'CormorantGaramond_400Regular', color: COLORS.text.secondary, textAlign: 'center', lineHeight: 24, marginBottom: 32, paddingHorizontal: 10 },
  skipButton: { marginTop: 20, paddingVertical: 12 },
  skipButtonText: { color: COLORS.text.muted, fontSize: 14, fontFamily: 'CormorantGaramond_400Regular' },
  verifyContainer: { alignItems: 'center', paddingVertical: 40 },
  verifyIconCircle: { width: 100, height: 100, borderRadius: 50, backgroundColor: COLORS.iconBg.peach, justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  verifyIconCircleLoading: { backgroundColor: COLORS.iconBg.lavender },
  verifySuccessCircle: { width: 100, height: 100, borderRadius: 50, backgroundColor: COLORS.accent.success, justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  verifyDescription: { fontSize: 16, fontFamily: 'CormorantGaramond_400Regular', color: COLORS.text.secondary, textAlign: 'center', lineHeight: 24, marginBottom: 32, paddingHorizontal: 10 },
});

export default styles;
