// Walking groups data
export const WALKING_GROUPS = [
  {
    id: 1,
    name: 'Wolfpack Group',
    startLocation: 'Squires Student Center',
    startCoords: { latitude: 37.2295934, longitude: -80.4179647 },
    destination: 'Ambler Johnston Hall',
    destCoords: { latitude: 37.2230926, longitude: -80.4209309 },
    departureMinutes: 120,
    createdAt: Date.now(),
    members: [
      { id: 'user1', name: 'Alex H.', isReady: true, isCreator: true },
      { id: 'user2', name: 'Jordan M.', isReady: true, isCreator: false },
      { id: 'user3', name: 'Sam K.', isReady: false, isCreator: false },
    ],
  },
  {
    id: 2,
    name: 'Night Owls',
    startLocation: 'Newman Library',
    startCoords: { latitude: 37.2288144, longitude: -80.4194466 },
    destination: 'D2 (Dietrick)',
    destCoords: { latitude: 37.22417, longitude: -80.42139 },
    departureMinutes: 120,
    createdAt: Date.now(),
    members: [
      { id: 'user4', name: 'Taylor B.', isReady: true, isCreator: true },
      { id: 'user5', name: 'Casey L.', isReady: true, isCreator: false },
    ],
  },
  {
    id: 3,
    name: 'Library Squad',
    startLocation: 'Torgersen Hall',
    startCoords: { latitude: 37.2297057, longitude: -80.4201748 },
    destination: 'Newman Library',
    destCoords: { latitude: 37.2288144, longitude: -80.4194466 },
    departureMinutes: 120,
    createdAt: Date.now(),
    members: [
      { id: 'user9', name: 'Jamie R.', isReady: true, isCreator: true },
      { id: 'user10', name: 'Drew T.', isReady: true, isCreator: false },
    ],
  },
  {
    id: 4,
    name: 'Drillfield Walkers',
    startLocation: 'Burruss Hall',
    startCoords: { latitude: 37.2284, longitude: -80.4236 },
    destination: 'War Memorial Hall',
    destCoords: { latitude: 37.2271281, longitude: -80.4171392 },
    departureMinutes: 120,
    createdAt: Date.now(),
    members: [
      { id: 'user11', name: 'Chris M.', isReady: true, isCreator: true },
      { id: 'user12', name: 'Pat L.', isReady: false, isCreator: false },
    ],
  },
];
